# Generated by Django 5.1.4 on 2024-12-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='mass',
            new_name='measure',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='measure_unit',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g'),
        ),
    ]
