# Generated by Django 5.1.4 on 2024-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurantmodel_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurantmodel',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
