# Generated by Django 5.1.4 on 2024-12-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantmodel_delivery_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchmodel',
            old_name='employee',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='manager',
            new_name='owner',
        ),
    ]
