# Generated by Django 5.1.4 on 2024-12-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_branchmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmodel',
            name='delivery_price',
        ),
    ]
