# Generated by Django 5.1.4 on 2024-12-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitemmodel_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='measure_unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.ordermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product_price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
