# Generated by Django 5.1.4 on 2024-12-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordermodel_branch_alter_ordermodel_status'),
        ('restaurants', '0008_alter_restaurantmodel_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.branchmodel'),
        ),
    ]
