# Generated by Django 5.1.4 on 2024-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('OWNER', 'OWNER'), ('MANAGER', 'MANAGER'), ('DELIVERY', 'DELIVERY'), ('CLIENT', 'CLIENT')], default='CLIENT', max_length=50),
        ),
    ]
