version: "3.11"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "wait-for-it -t 60 ${DB_HOST}:${DB_PORT} --   
              python manage.py migrate &&  
              python manage.py runserver 0.0.0.0:8000"
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - app_network


volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
