# Generated by Django 5.1.4 on 2024-12-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'verbose_name': 'Client Address', 'verbose_name_plural': 'Client Addresses'},
        ),
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together=set(),
        ),
    ]
